import cv2


# ARCHITECTURE
MODEL_DIR = 'some other directory'
IMAGE_DIR = 'some directory'


# MODEL PARAMETERS
DETECTOR_PATH = r"D:\CVFiles\ANNIE\Models\segmentor_binary_demo.h5"
CLASSIFIER_PATH = r"D:\CVFiles\ANNIE\Models\classifier_32.h5"
INPUT_HEIGHT = 64
INPUT_WIDTH = 64
INPUT_CHANNELS = 3
LAYERS = [32,64,128,256,512]
EPOCHS = 3
TEST_RATIO = 0.0
BATCH_SIZE = 2
PATIENCE = 2
BASELINE = 0.0
DROPOUT = 0.10
LOSS = 'mae'
ACTIVATION = 'selu'
FINAL_ACTIVATION = 'softmax'
OPTIMIZER = 'adam'
LEARN_RATE = 1e-5
POOL_SIZE = (2,2)
FINAL_POOL = (1,1)
METRIC = 'categorical_accuracy'
VAL_METRIC = 'val_categorical_accuracy'


# VIDEO SETTINGS
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FRAME_CHANNELS = 3
HUD_COLOR = (220,220,50)
HUD_ALPHA = 0.50
HUD_FONT = cv2.FONT_HERSHEY_DUPLEX
HUD_LINE_STYLE = cv2.LINE_AA
FPS_SMOOTHING = 5
SEARCH_SCALES = [2,3,4,6]
STOP_CAMERA_KEY = 'q'
DETECT_THRESH = 0.95
